/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) on 6/29/11 10:57 AM
 */
package gov.nasa.jpl.cdp.provenance.opmo;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> CauseWasControlledBy </li>
 *   <li> EffectWasControlledBy </li>
 *   <li> EndTime </li>
 *   <li> StartTime </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 6/29/11 10:57 AM
 */
public class WasControlledBy extends Edge {

    /** http://openprovenance.org/model/opmo#WasControlledBy */
	@SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://openprovenance.org/model/opmo#WasControlledBy", false);

    /** http://openprovenance.org/model/opmo#causeWasControlledBy */
	public static final URI CAUSEWASCONTROLLEDBY = new URIImpl("http://openprovenance.org/model/opmo#causeWasControlledBy",false);

    /** http://openprovenance.org/model/opmo#effectWasControlledBy */
	public static final URI EFFECTWASCONTROLLEDBY = new URIImpl("http://openprovenance.org/model/opmo#effectWasControlledBy",false);

    /** http://openprovenance.org/model/opmo#endTime */
	public static final URI ENDTIME = new URIImpl("http://openprovenance.org/model/opmo#endTime",false);

    /** http://openprovenance.org/model/opmo#startTime */
	public static final URI STARTTIME = new URIImpl("http://openprovenance.org/model/opmo#startTime",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
	@SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://openprovenance.org/model/opmo#causeWasControlledBy",false),
      new URIImpl("http://openprovenance.org/model/opmo#effectWasControlledBy",false),
      new URIImpl("http://openprovenance.org/model/opmo#endTime",false),
      new URIImpl("http://openprovenance.org/model/opmo#startTime",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected WasControlledBy ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public WasControlledBy ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public WasControlledBy ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public WasControlledBy ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public WasControlledBy ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of WasControlledBy  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static WasControlledBy  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, WasControlledBy.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://openprovenance.org/model/opmo#WasControlledBy).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends WasControlledBy> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, WasControlledBy.class );
	}

    /**
	 * Remove rdf:type WasControlledBy from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'EffectWasControlledByInverse' to this WasControlledBy instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllEffectWasControlledByInverse_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Process.EFFECTWASCONTROLLEDBYINVERSE, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'EffectWasControlledByInverse' to this WasControlledBy instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllEffectWasControlledByInverse_Inverse() {
		return Base.getAll_Inverse(this.model, Process.EFFECTWASCONTROLLEDBYINVERSE, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'EffectWasControlledByInverse' to this WasControlledBy instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllEffectWasControlledByInverse_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Process.EFFECTWASCONTROLLEDBYINVERSE, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@7f38f3d1 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, CAUSEWASCONTROLLEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@7f38f3d1 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasCauseWasControlledBy() {
		return Base.has(this.model, this.getResource(), CAUSEWASCONTROLLEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@7f38f3d1 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@7f38f3d1 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasCauseWasControlledBy( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}

     /**
     * Get all values of property CauseWasControlledBy as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCauseWasControlledBy_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, CAUSEWASCONTROLLEDBY);
	}
	
    /**
     * Get all values of property CauseWasControlledBy as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCauseWasControlledBy_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CAUSEWASCONTROLLEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property CauseWasControlledBy as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllCauseWasControlledBy_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), CAUSEWASCONTROLLEDBY);
	}

    /**
     * Get all values of property CauseWasControlledBy as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllCauseWasControlledBy_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property CauseWasControlledBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Agent> getAllCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, CAUSEWASCONTROLLEDBY, Agent.class);
	}
	
    /**
     * Get all values of property CauseWasControlledBy as a ReactorResult of Agent 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Agent> getAllCauseWasControlledBy_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, CAUSEWASCONTROLLEDBY, Agent.class);
	}

    /**
     * Get all values of property CauseWasControlledBy     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Agent> getAllCauseWasControlledBy() {
		return Base.getAll(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, Agent.class);
	}

    /**
     * Get all values of property CauseWasControlledBy as a ReactorResult of Agent 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Agent> getAllCauseWasControlledBy_as() {
		return Base.getAll_as(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, Agent.class);
	}
 
    /**
     * Adds a value to property CauseWasControlledBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addCauseWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Adds a value to property CauseWasControlledBy as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addCauseWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
    /**
     * Adds a value to property CauseWasControlledBy from an instance of Agent 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Agent value) {
		Base.add(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Adds a value to property CauseWasControlledBy from an instance of Agent 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addCauseWasControlledBy(Agent value) {
		Base.add(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
  

    /**
     * Sets a value of property CauseWasControlledBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setCauseWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Sets a value of property CauseWasControlledBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setCauseWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
    /**
     * Sets a value of property CauseWasControlledBy from an instance of Agent 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Agent value) {
		Base.set(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Sets a value of property CauseWasControlledBy from an instance of Agent 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setCauseWasControlledBy(Agent value) {
		Base.set(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
  


    /**
     * Removes a value of property CauseWasControlledBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeCauseWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Removes a value of property CauseWasControlledBy as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeCauseWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
    /**
     * Removes a value of property CauseWasControlledBy given as an instance of Agent 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeCauseWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Agent value) {
		Base.remove(model, instanceResource, CAUSEWASCONTROLLEDBY, value);
	}
	
    /**
     * Removes a value of property CauseWasControlledBy given as an instance of Agent 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeCauseWasControlledBy(Agent value) {
		Base.remove(this.model, this.getResource(), CAUSEWASCONTROLLEDBY, value);
	}
  
    /**
     * Removes all values of property CauseWasControlledBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllCauseWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, CAUSEWASCONTROLLEDBY);
	}
	
    /**
     * Removes all values of property CauseWasControlledBy	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllCauseWasControlledBy() {
		Base.removeAll(this.model, this.getResource(), CAUSEWASCONTROLLEDBY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2a89e0c6 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, EFFECTWASCONTROLLEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2a89e0c6 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasEffectWasControlledBy() {
		return Base.has(this.model, this.getResource(), EFFECTWASCONTROLLEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2a89e0c6 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@2a89e0c6 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasEffectWasControlledBy( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}

     /**
     * Get all values of property EffectWasControlledBy as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllEffectWasControlledBy_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, EFFECTWASCONTROLLEDBY);
	}
	
    /**
     * Get all values of property EffectWasControlledBy as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllEffectWasControlledBy_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, EFFECTWASCONTROLLEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property EffectWasControlledBy as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllEffectWasControlledBy_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), EFFECTWASCONTROLLEDBY);
	}

    /**
     * Get all values of property EffectWasControlledBy as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllEffectWasControlledBy_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property EffectWasControlledBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Process> getAllEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, EFFECTWASCONTROLLEDBY, Process.class);
	}
	
    /**
     * Get all values of property EffectWasControlledBy as a ReactorResult of Process 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Process> getAllEffectWasControlledBy_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, EFFECTWASCONTROLLEDBY, Process.class);
	}

    /**
     * Get all values of property EffectWasControlledBy     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Process> getAllEffectWasControlledBy() {
		return Base.getAll(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, Process.class);
	}

    /**
     * Get all values of property EffectWasControlledBy as a ReactorResult of Process 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Process> getAllEffectWasControlledBy_as() {
		return Base.getAll_as(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, Process.class);
	}
 
    /**
     * Adds a value to property EffectWasControlledBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addEffectWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Adds a value to property EffectWasControlledBy as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addEffectWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
    /**
     * Adds a value to property EffectWasControlledBy from an instance of Process 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Process value) {
		Base.add(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Adds a value to property EffectWasControlledBy from an instance of Process 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addEffectWasControlledBy(Process value) {
		Base.add(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
  

    /**
     * Sets a value of property EffectWasControlledBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setEffectWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Sets a value of property EffectWasControlledBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setEffectWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
    /**
     * Sets a value of property EffectWasControlledBy from an instance of Process 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Process value) {
		Base.set(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Sets a value of property EffectWasControlledBy from an instance of Process 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setEffectWasControlledBy(Process value) {
		Base.set(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
  


    /**
     * Removes a value of property EffectWasControlledBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeEffectWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Removes a value of property EffectWasControlledBy as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeEffectWasControlledBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
    /**
     * Removes a value of property EffectWasControlledBy given as an instance of Process 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeEffectWasControlledBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Process value) {
		Base.remove(model, instanceResource, EFFECTWASCONTROLLEDBY, value);
	}
	
    /**
     * Removes a value of property EffectWasControlledBy given as an instance of Process 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeEffectWasControlledBy(Process value) {
		Base.remove(this.model, this.getResource(), EFFECTWASCONTROLLEDBY, value);
	}
  
    /**
     * Removes all values of property EffectWasControlledBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllEffectWasControlledBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, EFFECTWASCONTROLLEDBY);
	}
	
    /**
     * Removes all values of property EffectWasControlledBy	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllEffectWasControlledBy() {
		Base.removeAll(this.model, this.getResource(), EFFECTWASCONTROLLEDBY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@61aa1db8 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, ENDTIME);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@61aa1db8 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasEndTime() {
		return Base.has(this.model, this.getResource(), ENDTIME);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@61aa1db8 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, ENDTIME, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@61aa1db8 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasEndTime( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), ENDTIME, value);
	}

     /**
     * Get all values of property EndTime as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllEndTime_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, ENDTIME);
	}
	
    /**
     * Get all values of property EndTime as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllEndTime_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ENDTIME, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property EndTime as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllEndTime_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), ENDTIME);
	}

    /**
     * Get all values of property EndTime as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllEndTime_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), ENDTIME, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property EndTime     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<OTime> getAllEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, ENDTIME, OTime.class);
	}
	
    /**
     * Get all values of property EndTime as a ReactorResult of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<OTime> getAllEndTime_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, ENDTIME, OTime.class);
	}

    /**
     * Get all values of property EndTime     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<OTime> getAllEndTime() {
		return Base.getAll(this.model, this.getResource(), ENDTIME, OTime.class);
	}

    /**
     * Get all values of property EndTime as a ReactorResult of OTime 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<OTime> getAllEndTime_as() {
		return Base.getAll_as(this.model, this.getResource(), ENDTIME, OTime.class);
	}
 
    /**
     * Adds a value to property EndTime as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addEndTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Adds a value to property EndTime as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addEndTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), ENDTIME, value);
	}
    /**
     * Adds a value to property EndTime from an instance of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.add(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Adds a value to property EndTime from an instance of OTime 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addEndTime(OTime value) {
		Base.add(this.model, this.getResource(), ENDTIME, value);
	}
  

    /**
     * Sets a value of property EndTime from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setEndTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Sets a value of property EndTime from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setEndTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), ENDTIME, value);
	}
    /**
     * Sets a value of property EndTime from an instance of OTime 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.set(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Sets a value of property EndTime from an instance of OTime 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setEndTime(OTime value) {
		Base.set(this.model, this.getResource(), ENDTIME, value);
	}
  


    /**
     * Removes a value of property EndTime as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeEndTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Removes a value of property EndTime as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeEndTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), ENDTIME, value);
	}
    /**
     * Removes a value of property EndTime given as an instance of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeEndTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.remove(model, instanceResource, ENDTIME, value);
	}
	
    /**
     * Removes a value of property EndTime given as an instance of OTime 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeEndTime(OTime value) {
		Base.remove(this.model, this.getResource(), ENDTIME, value);
	}
  
    /**
     * Removes all values of property EndTime     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllEndTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, ENDTIME);
	}
	
    /**
     * Removes all values of property EndTime	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllEndTime() {
		Base.removeAll(this.model, this.getResource(), ENDTIME);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1e235551 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, STARTTIME);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1e235551 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasStartTime() {
		return Base.has(this.model, this.getResource(), STARTTIME);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1e235551 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, STARTTIME, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1e235551 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasStartTime( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), STARTTIME, value);
	}

     /**
     * Get all values of property StartTime as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllStartTime_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, STARTTIME);
	}
	
    /**
     * Get all values of property StartTime as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllStartTime_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, STARTTIME, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property StartTime as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllStartTime_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), STARTTIME);
	}

    /**
     * Get all values of property StartTime as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllStartTime_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), STARTTIME, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property StartTime     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<OTime> getAllStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, STARTTIME, OTime.class);
	}
	
    /**
     * Get all values of property StartTime as a ReactorResult of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<OTime> getAllStartTime_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, STARTTIME, OTime.class);
	}

    /**
     * Get all values of property StartTime     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<OTime> getAllStartTime() {
		return Base.getAll(this.model, this.getResource(), STARTTIME, OTime.class);
	}

    /**
     * Get all values of property StartTime as a ReactorResult of OTime 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<OTime> getAllStartTime_as() {
		return Base.getAll_as(this.model, this.getResource(), STARTTIME, OTime.class);
	}
 
    /**
     * Adds a value to property StartTime as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addStartTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Adds a value to property StartTime as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addStartTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), STARTTIME, value);
	}
    /**
     * Adds a value to property StartTime from an instance of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.add(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Adds a value to property StartTime from an instance of OTime 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addStartTime(OTime value) {
		Base.add(this.model, this.getResource(), STARTTIME, value);
	}
  

    /**
     * Sets a value of property StartTime from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setStartTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Sets a value of property StartTime from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setStartTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), STARTTIME, value);
	}
    /**
     * Sets a value of property StartTime from an instance of OTime 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.set(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Sets a value of property StartTime from an instance of OTime 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setStartTime(OTime value) {
		Base.set(this.model, this.getResource(), STARTTIME, value);
	}
  


    /**
     * Removes a value of property StartTime as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeStartTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Removes a value of property StartTime as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeStartTime( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), STARTTIME, value);
	}
    /**
     * Removes a value of property StartTime given as an instance of OTime 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeStartTime(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, OTime value) {
		Base.remove(model, instanceResource, STARTTIME, value);
	}
	
    /**
     * Removes a value of property StartTime given as an instance of OTime 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeStartTime(OTime value) {
		Base.remove(this.model, this.getResource(), STARTTIME, value);
	}
  
    /**
     * Removes all values of property StartTime     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllStartTime( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, STARTTIME);
	}
	
    /**
     * Removes all values of property StartTime	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllStartTime() {
		Base.removeAll(this.model, this.getResource(), STARTTIME);
	}
 }