/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) on 10/2/12 2:28 PM
 */
package gov.nasa.jpl.cdp.provenance.prov;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> ProcessingStep </li>
 *   <li> RuntimeEnvironment </li>
 * </ul>
 *
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 10/2/12 2:28 PM
 */
public class Session extends Bundle {

    /** http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#Session */
	@SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#Session", false);

    /** http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasProcessingStep */
	public static final URI PROCESSINGSTEP = new URIImpl("http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasProcessingStep",false);

    /** http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasRuntimeEnvironment */
	public static final URI RUNTIMEENVIRONMENT = new URIImpl("http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasRuntimeEnvironment",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
	@SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasProcessingStep",false),
      new URIImpl("http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#hasRuntimeEnvironment",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Session ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Session ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Session ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Session ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Session ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Session  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Session  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Session.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://jpl.nasa.gov/ontologies/2012/8/prov-es.owl#Session).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Session> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Session.class );
	}

    /**
	 * Remove rdf:type Session from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods


    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@e0c078 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, PROCESSINGSTEP);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@e0c078 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasProcessingStep() {
		return Base.has(this.model, this.getResource(), PROCESSINGSTEP);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@e0c078 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, PROCESSINGSTEP, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@e0c078 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasProcessingStep( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), PROCESSINGSTEP, value);
	}

     /**
     * Get all values of property ProcessingStep as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllProcessingStep_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, PROCESSINGSTEP);
	}
	
    /**
     * Get all values of property ProcessingStep as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllProcessingStep_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, PROCESSINGSTEP, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property ProcessingStep as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllProcessingStep_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), PROCESSINGSTEP);
	}

    /**
     * Get all values of property ProcessingStep as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllProcessingStep_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), PROCESSINGSTEP, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property ProcessingStep     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<ProcessingStep> getAllProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, PROCESSINGSTEP, ProcessingStep.class);
	}
	
    /**
     * Get all values of property ProcessingStep as a ReactorResult of ProcessingStep 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<ProcessingStep> getAllProcessingStep_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, PROCESSINGSTEP, ProcessingStep.class);
	}

    /**
     * Get all values of property ProcessingStep     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<ProcessingStep> getAllProcessingStep() {
		return Base.getAll(this.model, this.getResource(), PROCESSINGSTEP, ProcessingStep.class);
	}

    /**
     * Get all values of property ProcessingStep as a ReactorResult of ProcessingStep 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<ProcessingStep> getAllProcessingStep_as() {
		return Base.getAll_as(this.model, this.getResource(), PROCESSINGSTEP, ProcessingStep.class);
	}
 
    /**
     * Adds a value to property ProcessingStep as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addProcessingStep( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Adds a value to property ProcessingStep as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addProcessingStep( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
    /**
     * Adds a value to property ProcessingStep from an instance of ProcessingStep 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, ProcessingStep value) {
		Base.add(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Adds a value to property ProcessingStep from an instance of ProcessingStep 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addProcessingStep(ProcessingStep value) {
		Base.add(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
  

    /**
     * Sets a value of property ProcessingStep from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setProcessingStep( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Sets a value of property ProcessingStep from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setProcessingStep( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
    /**
     * Sets a value of property ProcessingStep from an instance of ProcessingStep 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, ProcessingStep value) {
		Base.set(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Sets a value of property ProcessingStep from an instance of ProcessingStep 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setProcessingStep(ProcessingStep value) {
		Base.set(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
  


    /**
     * Removes a value of property ProcessingStep as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeProcessingStep( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Removes a value of property ProcessingStep as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeProcessingStep( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
    /**
     * Removes a value of property ProcessingStep given as an instance of ProcessingStep 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeProcessingStep(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, ProcessingStep value) {
		Base.remove(model, instanceResource, PROCESSINGSTEP, value);
	}
	
    /**
     * Removes a value of property ProcessingStep given as an instance of ProcessingStep 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeProcessingStep(ProcessingStep value) {
		Base.remove(this.model, this.getResource(), PROCESSINGSTEP, value);
	}
  
    /**
     * Removes all values of property ProcessingStep     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllProcessingStep( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, PROCESSINGSTEP);
	}
	
    /**
     * Removes all values of property ProcessingStep	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllProcessingStep() {
		Base.removeAll(this.model, this.getResource(), PROCESSINGSTEP);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@115bbc has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, RUNTIMEENVIRONMENT);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@115bbc has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasRuntimeEnvironment() {
		return Base.has(this.model, this.getResource(), RUNTIMEENVIRONMENT);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@115bbc has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@115bbc has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasRuntimeEnvironment( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}

     /**
     * Get all values of property RuntimeEnvironment as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllRuntimeEnvironment_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, RUNTIMEENVIRONMENT);
	}
	
    /**
     * Get all values of property RuntimeEnvironment as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllRuntimeEnvironment_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, RUNTIMEENVIRONMENT, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property RuntimeEnvironment as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllRuntimeEnvironment_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), RUNTIMEENVIRONMENT);
	}

    /**
     * Get all values of property RuntimeEnvironment as a ReactorResult of RDF2Go nodes 
     * @return a List of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllRuntimeEnvironment_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), RUNTIMEENVIRONMENT, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property RuntimeEnvironment     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<RuntimeEnvironment> getAllRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, RUNTIMEENVIRONMENT, RuntimeEnvironment.class);
	}
	
    /**
     * Get all values of property RuntimeEnvironment as a ReactorResult of RuntimeEnvironment 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<RuntimeEnvironment> getAllRuntimeEnvironment_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, RUNTIMEENVIRONMENT, RuntimeEnvironment.class);
	}

    /**
     * Get all values of property RuntimeEnvironment     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<RuntimeEnvironment> getAllRuntimeEnvironment() {
		return Base.getAll(this.model, this.getResource(), RUNTIMEENVIRONMENT, RuntimeEnvironment.class);
	}

    /**
     * Get all values of property RuntimeEnvironment as a ReactorResult of RuntimeEnvironment 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<RuntimeEnvironment> getAllRuntimeEnvironment_as() {
		return Base.getAll_as(this.model, this.getResource(), RUNTIMEENVIRONMENT, RuntimeEnvironment.class);
	}
 
    /**
     * Adds a value to property RuntimeEnvironment as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addRuntimeEnvironment( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Adds a value to property RuntimeEnvironment as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addRuntimeEnvironment( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
    /**
     * Adds a value to property RuntimeEnvironment from an instance of RuntimeEnvironment 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, RuntimeEnvironment value) {
		Base.add(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Adds a value to property RuntimeEnvironment from an instance of RuntimeEnvironment 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addRuntimeEnvironment(RuntimeEnvironment value) {
		Base.add(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
  

    /**
     * Sets a value of property RuntimeEnvironment from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setRuntimeEnvironment( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Sets a value of property RuntimeEnvironment from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setRuntimeEnvironment( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
    /**
     * Sets a value of property RuntimeEnvironment from an instance of RuntimeEnvironment 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, RuntimeEnvironment value) {
		Base.set(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Sets a value of property RuntimeEnvironment from an instance of RuntimeEnvironment 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setRuntimeEnvironment(RuntimeEnvironment value) {
		Base.set(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
  


    /**
     * Removes a value of property RuntimeEnvironment as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removeRuntimeEnvironment( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Removes a value of property RuntimeEnvironment as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removeRuntimeEnvironment( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
    /**
     * Removes a value of property RuntimeEnvironment given as an instance of RuntimeEnvironment 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removeRuntimeEnvironment(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, RuntimeEnvironment value) {
		Base.remove(model, instanceResource, RUNTIMEENVIRONMENT, value);
	}
	
    /**
     * Removes a value of property RuntimeEnvironment given as an instance of RuntimeEnvironment 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removeRuntimeEnvironment(RuntimeEnvironment value) {
		Base.remove(this.model, this.getResource(), RUNTIMEENVIRONMENT, value);
	}
  
    /**
     * Removes all values of property RuntimeEnvironment     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllRuntimeEnvironment( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, RUNTIMEENVIRONMENT);
	}
	
    /**
     * Removes all values of property RuntimeEnvironment	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllRuntimeEnvironment() {
		Base.removeAll(this.model, this.getResource(), RUNTIMEENVIRONMENT);
	}
 }